<?php

declare(strict_types=1);

namespace Inspector\Laravel\Tests;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Inspector\Laravel\Facades\Inspector;
use Inspector\Laravel\Middleware\WebRequestMonitoring;
use Inspector\Models\Transaction;

class MiddlewareTest extends BasicTestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        // test the middleware
        Route::match(['get', 'post'], 'test', function (Request $request): void {
            // do nothing
        })->middleware(WebRequestMonitoring::class);

    }

    public function testIsRecording(): void
    {
        $this->assertTrue(Inspector::isRecording());
        $this->assertTrue(Inspector::needTransaction());

        $this->get('test');

        $this->assertFalse(Inspector::needTransaction());
        $this->assertInstanceOf(Transaction::class, Inspector::transaction());
    }

    public function testResult(): void
    {
        $response = $this->get('test');

        $this->assertEquals($response->getStatusCode(), Inspector::transaction()->result);

        $this->assertArrayHasKey('Response', Inspector::transaction()->getContext());
    }

    public function testContext(): void
    {

        $this->post('test', ['foo' => 'bar']);

        // $this->assertArrayHasKey('Request Body', Inspector::transaction()->getContext());
        $this->assertArrayHasKey('Response', Inspector::transaction()->getContext());
    }
}
